// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrhuvqxnlotcijzwljqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyaHV2cXhubG90Y2lqendsanFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTU0ODksImV4cCI6MjA1ODEzMTQ4OX0.qiEqMBXWtXGUDR2PAjg6-FZeIPfhZvfRzO2vgTPXOqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);